# -*- coding: utf-8 -*-
"""
DEPRECATED — This Colab export has been reorganized into the project modules.
See: config.py, data/, model/, training/, evaluation/, tests/, scripts/

Original Colab notebook export (kept for reference).
"""
"""Untitled7 (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YCHJojNpNf14eqjNVuBkMMkRitGK8pXk

Working: Textual Encoder, Video Encoder, Decoder, Full model wiring, Multi-resolution loss
Next: training loop (handoff.md Step 4)

# Textual Encoder
"""

!pip install gensim --quiet

import torch
import torch.nn as nn
import numpy as np
import gensim.downloader as api

print("PyTorch:", torch.__version__)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device :", device)

def load_word2vec():
    """
    Download & return the Google News Word2Vec model (300-dim).

    Returns
    -------
    gensim.models.KeyedVectors
        vocab size ~3 M words, vector size = 300
    """
    print("Downloading Word2Vec (Google News 300d) — ~1.5 GB, runs once ...")
    model = api.load("word2vec-google-news-300")
    print(f"Done.  vocab={len(model):,}  dim={model.vector_size}")
    return model


word2vec = load_word2vec()

"""PyTorch needs to stack them into a single tensor, which means every sentence must have the same shape.
```
"a man running"     → (20, 300)   [17 rows of zeros appended]
"a man in dark..."  → (20, 300)   [14 rows of zeros appended]
"small white..."    → (20, 300)   [13 rows of zeros appended]
                       ↓
              stack → (B=3, 20, 300)  ✅ valid tensor
```
"""

# ---------------------------------------------------------------------------
# CELL 4 — sentence_to_embedding
#
# Converts one raw sentence into a padded (max_len × 300) float matrix.
#
# Paper:
#   "Each word of the input sentence is represented as a 300-dimensional
#    word2vec embedding, without any further preprocessing.
#    Each sentence is additionally padded to have the same size."
# ---------------------------------------------------------------------------

def sentence_to_embedding(
    sentence: str,
    word2vec_model,
    max_len: int = 20, # PyTorch needs to stack them into a single tensor, which means every sentence must have the same shape
) -> torch.Tensor:
    """
    Sentence string → padded word-embedding matrix.

    Parameters
    ----------
    sentence       : raw text, e.g. "a man in dark suit standing on the back"
    word2vec_model : gensim KeyedVectors (300-dim)
    max_len        : pad or truncate to this many tokens (paper uses ~20)

 a 10-word sentence is represented by a 10 × 300 matrix
    Returns
    -------
    torch.FloatTensor  shape (max_len, 300)
        Rows beyond the sentence length are zero-padded.
        OOV words are also zero-filled.
    """
    tokens    = sentence.lower().split()
    embed_dim = word2vec_model.vector_size          # 300

    # Start with an all-zero matrix (handles both padding and OOV)
    matrix = np.zeros((max_len, embed_dim), dtype=np.float32)

    for i, token in enumerate(tokens[:max_len]):    # truncate if too long
        if token in word2vec_model:
            matrix[i] = word2vec_model[token]
        # OOV → stays as zero vector

    return torch.from_numpy(matrix)                 # (max_len, 300)

# ---------------------------------------------------------------------------
# CELL 5 — TextualEncoder  (the "Word2Vec Embedding → CNN" block in Fig. 2)
#
# Paper (Sec 3.1):
#   "The network consists of a single 1D convolutional layer with a temporal
#    filter size equal to 2 and with the same output dimension as the word2vec
#    representation. After the convolutional layer we apply the ReLU activation
#    function and perform max-pooling to obtain a representation for the whole
#    sentence."
# ---------------------------------------------------------------------------

class TextualEncoder(nn.Module):
    """
    1D-CNN sentence encoder from Gavrilyuk et al. CVPR 2018, Section 3.1.

    Architecture
    ------------
    Input  : (B, max_len, 300)  — batch of padded word-embedding matrices
                                   (produced by sentence_to_embedding)
    Step 1 : permute → (B, 300, max_len)   [Conv1D wants channels-first]
    Step 2 : Conv1D(in=300, out=300, k=2)  → (B, 300, max_len-1)
    Step 3 : ReLU
    Step 4 : global max-pool over time     → (B, 300)
    Output : (B, 300)  — one vector per sentence

    This 300-dim vector is later fed into three separate FC layers inside
    the decoder to produce dynamic convolutional filters at resolutions
    32×32 (832-ch), 128×128 (256-ch), and 512×512 (128-ch).

    NOTE: Word embeddings are created *outside* this module (frozen).
          Only the Conv1D weights are learned.
    """

    def __init__(self, embed_dim: int = 300, kernel_size: int = 2):
        super().__init__()

        # Single 1-D convolutional layer
        # kernel_size=2 means it looks at pairs of adjacent word vectors
        self.conv1d = nn.Conv1d(
            in_channels=embed_dim,    # 300  — word2vec dim
            out_channels=embed_dim,   # 300  — "same output dimension"
            kernel_size=kernel_size,  # 2    — "temporal filter size equal to 2"
            padding=0,                # no padding; max-pool handles variable len
        )
        self.relu = nn.ReLU()

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Parameters
        ----------
        x : torch.FloatTensor  shape (B, max_len, 300)

        Returns
        -------
        torch.FloatTensor  shape (B, 300)
        """
        # Conv1D in PyTorch expects (B, C_in, L), so move the channel dim first
        x = x.permute(0, 2, 1)           # (B, 300, max_len)

        x = self.conv1d(x)                # (B, 300, max_len - 1)
        x = self.relu(x)                  # (B, 300, max_len - 1)

        # Global max-pool over the time dimension → fixed-size sentence vector
        x = x.max(dim=-1).values          # (B, 300)

        return x

# ---------------------------------------------------------------------------
# CELL 6 — encode_sentence  (convenience wrapper for inference)
# ---------------------------------------------------------------------------

def encode_sentence(
    sentence: str,
    word2vec_model,
    encoder: TextualEncoder,
    max_len: int = 20,
) -> torch.Tensor:
    """
    End-to-end helper: raw sentence → 300-dim feature vector.

    Parameters
    ----------
    sentence       : e.g. "a man in dark suit standing on the back"
    word2vec_model : loaded gensim KeyedVectors
    encoder        : TextualEncoder instance (can be on CPU or GPU)
    max_len        : same value used during training

    Returns
    -------
    torch.FloatTensor  shape (300,)
    """
    # Derive the device from the encoder's parameters
    enc_device = next(encoder.parameters()).device

    emb   = sentence_to_embedding(sentence, word2vec_model, max_len)  # (L, 300)
    emb   = emb.unsqueeze(0).to(enc_device)                           # (1, L, 300)

    encoder.eval()
    with torch.no_grad():
        feat = encoder(emb)   # (1, 300)

    return feat.squeeze(0)    # (300,)

# ---------------------------------------------------------------------------
# CELL 7 — Sanity check
# ---------------------------------------------------------------------------

MAX_LEN = 20

encoder = TextualEncoder(embed_dim=300, kernel_size=2).to(device)
encoder.eval()

# Sentences taken directly from Figure 2 and Figure 4 of the paper
test_sentences = [
    "a man in dark suit standing on the back",   # Fig. 2 example query
    "car jumping into the water",                 # Fig. 4
    "small white fluffy puppy biting the cat",   # Fig. 4
    "woman in green dress is walking on the street",
]

print("=" * 60)
print("Textual Encoder — Sanity Check")
print("=" * 60)

for sent in test_sentences:
    # --- Step-by-step so you can see each intermediate shape ---
    emb_matrix = sentence_to_embedding(sent, word2vec, MAX_LEN)   # (20, 300)
    emb_batch  = emb_matrix.unsqueeze(0).to(device)               # (1, 20, 300)

    with torch.no_grad():
        feat = encoder(emb_batch)                                  # (1, 300)

    # How many tokens were actually in the word2vec vocab?
    tokens   = sent.lower().split()
    in_vocab = sum(1 for t in tokens if t in word2vec)

    print(f"\n  Query   : '{sent}'")
    print(f"  Tokens  : {len(tokens)}  ({in_vocab} found in Word2Vec vocab)")
    print(f"  Shapes  : embedding {emb_batch.shape} → feature {feat.shape}")
    print(f"  Feature : min={feat.min():.4f}  max={feat.max():.4f}  "
          f"mean={feat.mean():.4f}")

print("\n" + "=" * 60)
print("✅  Output is (B=1, 300).  Ready to feed into the FC → dynamic-filter layers.")
print("=" * 60)

# Quick parameter count
n_params = sum(p.numel() for p in encoder.parameters() if p.requires_grad)
print(f"\nLearnable parameters in TextualEncoder: {n_params:,}")
# Expected: Conv1d weight = 300×300×2 = 180,000 + bias 300 = 180,300

"""# Video Encoder"""

!apt-get install -qq git-lfs
!git lfs install
!git clone https://github.com/piergiaj/pytorch-i3d.git
#
import sys
sys.path.insert(0, '/content/pytorch-i3d')
#
# # Verify weights file exists and isn't just an LFS pointer (should be ~28 MB)
import os
size = os.path.getsize('/content/pytorch-i3d/models/rgb_imagenet.pt')
print(f"Weight file size: {size / 1e6:.1f} MB  {'✓' if size > 1e6 else '✗ LFS pointer only!'}")

import os
import glob
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import matplotlib.gridspec as gridspec

from pytorch_i3d import InceptionI3d

print("PyTorch:", torch.__version__)
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device :", device)

# ---------------------------------------------------------------------------
# CELL 3 — load_i3d
#
# Key decision: final_endpoint='Mixed_4f'
#
# I3D spatial size at each block (with 512×512 input):
#   Conv3d_1a  stride-2  → 256×256
#   MaxPool_2a stride-2  → 128×128
#   MaxPool_3a stride-2  →  64×64
#   MaxPool_4a stride-2  →  32×32   ← Mixed_4f lives here, 832 channels ✓
#   MaxPool_5a stride-2  →  16×16   ← paper stops BEFORE this
#   Mixed_5b/5c           →  16×16
#
# Paper (Sec 3.2):
#   "We use the output of the inception block before the last max-pooling
#    layer of the I3D network."
#   → That's Mixed_4f: 832 channels, 32×32 for 512×512 input.
# ---------------------------------------------------------------------------
WEIGHTS_PATH = "/content/pytorch-i3d/models/rgb_imagenet.pt"

def load_i3d(weights_path: str = WEIGHTS_PATH) -> InceptionI3d:
    """
    Load the FULL RGB I3D pre-trained on ImageNet + Kinetics.

    No final_endpoint — we load all layers and control the stopping
    point ourselves inside VideoEncoder.forward().

    Expected params: ~12.3 M  (full model up to Logits)
    """
    i3d = InceptionI3d(num_classes=400, in_channels=3)   # default endpoint = 'Logits'
    state = torch.load(weights_path, map_location="cpu")
    i3d.load_state_dict(state, strict=False)              # strict=False handles logits layer size
    i3d.eval()

    total = sum(p.numel() for p in i3d.parameters())
    print(f"I3D loaded   : {weights_path}")
    print(f"Total params : {total:,}   (expected ~12,298,864)")
    return i3d


i3d_backbone = load_i3d()

# ---------------------------------------------------------------------------
# CELL 4 — load_video_frames
#
# Data layout from your folder (Image 2):
#   JPEGImages/
#     0a2f2bd294/
#       00000.jpg
#       00005.jpg   ← spaced every 5 frames
#       ...
#       00095.jpg   (20 total)
#
# We sample N=16 evenly-spaced frames from whatever is in the folder.
# Paper (Sec 5.1 ablation): N=16 gives best results.
# ---------------------------------------------------------------------------

def load_video_frames(
    video_dir: str,
    num_frames: int = 16,
    frame_size: int = 512,
) -> tuple:
    """
    Load N evenly-spaced JPEG frames from one video folder.

    Parameters
    ----------
    video_dir  : path to the video folder  (e.g. .../JPEGImages/0a2f2bd294)
    num_frames : N frames to sample (paper uses 16)
    frame_size : resize each frame to (frame_size, frame_size)
                 512 → matches paper exactly (32×32 feature map)
                 224 → faster sanity check (14×14 feature map)

    Returns
    -------
    tensor : torch.FloatTensor  shape (1, 3, N, H, W),  values ∈ [-1, 1]
    paths  : list[str]  — selected file paths (for visualisation)
    """
    all_paths = sorted(glob.glob(os.path.join(video_dir, "*.jpg")))
    if not all_paths:
        raise FileNotFoundError(f"No .jpg files in: {video_dir}")

    # Evenly-spaced indices (with repetition if video is shorter than num_frames)
    indices  = np.linspace(0, len(all_paths) - 1, num_frames, dtype=int)
    selected = [all_paths[i] for i in indices]

    frames = []
    for path in selected:
        img = Image.open(path).convert("RGB")
        img = img.resize((frame_size, frame_size), Image.BILINEAR)
        arr = np.array(img, dtype=np.float32) / 255.0   # [0, 1]
        arr = arr * 2.0 - 1.0                            # [-1, 1]  I3D pre-training norm
        frames.append(arr)                               # (H, W, 3)

    video = np.stack(frames)             # (N, H, W, 3)
    video = video.transpose(3, 0, 1, 2) # (3, N, H, W)
    tensor = torch.from_numpy(video).unsqueeze(0)  # (1, 3, N, H, W)

    print(f"Loaded {num_frames}/{len(all_paths)} frames from '{os.path.basename(video_dir)}'")
    print(f"  Files selected : {[os.path.basename(p) for p in selected]}")
    print(f"  Tensor shape   : {tensor.shape}   dtype={tensor.dtype}")
    return tensor, selected

# ---------------------------------------------------------------------------
# CELL 5 — VideoEncoder
#
# Wraps I3D and adds the three post-processing steps from Section 3.2:
#   1. Temporal average pooling
#   2. L2-normalisation per spatial position
#   3. Append (y, x) coordinate channels
# ---------------------------------------------------------------------------
# ---------------------------------------------------------------------------
# CELL 5 (FIXED) — VideoEncoder
#
# The forward() now manually steps through each I3D layer and stops
# at mixed_4f — giving (B, 832, T', H', W') as required by the paper.
# ---------------------------------------------------------------------------

class VideoEncoder(nn.Module):
    """
    Video Encoder — Gavrilyuk et al. CVPR 2018, Section 3.2.

    Architecture (Figure 2 — the red-circled Video Encoder block):

        (B, 3, N, 512, 512)
            ↓  I3D layers up to mixed_4f (manually stepped)
        (B, 832, T', 32, 32)    T'≈4 for N=16  |  32×32 for 512×512 input
            ↓  avg-pool over T'
        (B, 832, 32, 32)
            ↓  L2-normalise per spatial position (over channel dim)
        (B, 832, 32, 32)
            ↓  append (y, x) coordinate grids
        (B, 834, 32, 32)

    Why mixed_4f?
        4 spatial halvings before it:  512 → 256 → 128 → 64 → 32
        832 output channels match the dynamic filter size in the decoder.
    Video Encoder — Gavrilyuk et al. CVPR 2018, Section 3.2.

    Uses a forward hook on Mixed_4f to capture (B, 832, T', H', W'),
    then applies avg-pool → L2-norm → spatial coords.

    This approach is naming-convention agnostic: it searches the model's
    module tree for the Mixed_4f InceptionModule, so it works regardless
    of which pytorch-i3d fork or version you cloned.
    """

    def __init__(self, i3d: InceptionI3d):
        super().__init__()
        self.i3d   = i3d
        self._feat = {}          # hook writes here; forward reads here

        # --- Find mixed_4f and attach hook ---
        target_module, target_name = self._find_mixed4f(i3d)
        self._hook = target_module.register_forward_hook(
            lambda m, inp, out: self._feat.update({'mixed_4f': out})
        )
        print(f"VideoEncoder: hooked '{target_name}'  "
              f"(type={type(target_module).__name__})")

    # ------------------------------------------------------------------
    # Layer search
    # ------------------------------------------------------------------

    @staticmethod
    def _find_mixed4f(i3d: nn.Module):
        """
        Search the module tree for mixed_4f using three strategies:

        Strategy 1 — exact attribute match (covers most pytorch-i3d versions)
            self.mixed_4f  or  self.Mixed_4f

        Strategy 2 — named_modules() substring match
            Matches any module whose dotted name contains 'mixed_4f'
            (case-insensitive), e.g. 'inception_i3d/Mixed_4f'

        Strategy 3 — output channel count (fallback, fragile)
            The 13th InceptionModule in traversal order is mixed_4f.
            Only used if strategies 1 & 2 both fail.

        Raises RuntimeError with a helpful dump if nothing found.
        """
        # Strategy 1: direct attribute
        for attr_name in ('mixed_4f', 'Mixed_4f'):
            if hasattr(i3d, attr_name):
                return getattr(i3d, attr_name), attr_name

        # Strategy 2: substring search through named_modules
        for name, mod in i3d.named_modules():
            normalised = name.lower().replace('/', '_').replace('-', '_')
            if 'mixed_4f' in normalised:
                return mod, name

        # Strategy 3: count InceptionModules (mixed_4f is the 5th one)
        #   3b, 3c, 4b, 4c, 4d, 4e → mixed_4f is the 6th inception block
        inception_count = 0
        for name, mod in i3d.named_modules():
            if type(mod).__name__ == 'InceptionModule':
                inception_count += 1
                if inception_count == 6:            # 3b=1, 3c=2, 4b=3, 4c=4, 4d=5... wait
                    return mod, f"{name} (strategy-3 fallback)"

        # Nothing found — dump the tree so the user can report back
        all_names = [n for n, _ in i3d.named_modules() if n]
        raise RuntimeError(
            "Could not locate Mixed_4f in the I3D model.\n"
            f"All module names:\n" + "\n".join(f"  {n}" for n in all_names)
        )

    # ------------------------------------------------------------------
    # Spatial coordinate helper
    # ------------------------------------------------------------------

    @staticmethod
    def _append_spatial_coords(x: torch.Tensor) -> torch.Tensor:
        """
        Append y-grid and x-grid as 2 extra channels.  Values ∈ [-1, 1].
        Paper (Sec 3.2): "allows learning spatial qualifiers like 'left of'."
        """
        B, C, H, W = x.shape
        y_line = torch.linspace(-1, 1, H, device=x.device)
        x_line = torch.linspace(-1, 1, W, device=x.device)
        gy, gx = torch.meshgrid(y_line, x_line, indexing="ij")
        gy = gy.unsqueeze(0).unsqueeze(0).expand(B, -1, -1, -1)
        gx = gx.unsqueeze(0).unsqueeze(0).expand(B, -1, -1, -1)
        return torch.cat([x, gy, gx], dim=1)

    # ------------------------------------------------------------------
    # Forward
    # ------------------------------------------------------------------

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        """
        Args:
            x : (B, 3, N, H, W)  values ∈ [-1, 1]
        Returns:
            (B, 834, H', W')   H'=W'=32 for 512×512 input
        """
        self._feat.clear()

        # Run full I3D forward; the hook captures Mixed_4f output mid-way
        _ = self.i3d(x)

        feat = self._feat['mixed_4f']       # (B, 832, T', H', W')
        feat = feat.mean(dim=2)             # avg-pool over T'   → (B, 832, H', W')
        feat = F.normalize(feat, p=2, dim=1)                     # L2-norm per position
        feat = self._append_spatial_coords(feat)                 # (B, 834, H', W')
        return feat

    def __del__(self):
        """Clean up the hook when the encoder is garbage-collected."""
        if hasattr(self, '_hook'):
            self._hook.remove()

# ---------------------------------------------------------------------------
# CELL 6 — Sanity check + visualisation
#
# Expected output with FRAME_SIZE=512:  (1, 834, 32, 32)
# Expected output with FRAME_SIZE=224:  (1, 834, 14, 14)
#
# Visualisation shows:
#   Row 0: 4 sampled input frames + y-coordinate channel (sanity check)
#   Row 1: mean feature map, 3 individual channels, overlay on middle frame
# ---------------------------------------------------------------------------


# ---- CONFIGURE THIS ----
VIDEO_DIR  = "/content/JPEGImages/0a2f2bd294"
NUM_FRAMES = 16
FRAME_SIZE = 512   # 512 = paper-accurate (32×32 map). Use 224 if you hit OOM.

# ---- Load video ----
video_tensor, frame_paths = load_video_frames(VIDEO_DIR, NUM_FRAMES, FRAME_SIZE)
video_tensor = video_tensor.to(device)

# ---- Build encoder ----
encoder = VideoEncoder(i3d_backbone.to(device))
encoder.eval()

# ---- Forward pass ----
print(f"\nRunning VideoEncoder (FRAME_SIZE={FRAME_SIZE}, this may take ~60s on CPU)...")
with torch.no_grad():
    feat_map = encoder(video_tensor)                   # (1, 834, H', W')

print(f"\nVideoEncoder output : {tuple(feat_map.shape)}")
print(f"  832 visual ch     + 2 coord ch = {feat_map.shape[1]} total channels")
print(f"  Spatial map       : {feat_map.shape[2]} × {feat_map.shape[3]}")

# ---- Prepare arrays ----
feat_np  = feat_map[0].cpu().numpy()                  # (834, H', W')
H_prime  = feat_np.shape[1]

# Middle frame as reference image
mid_img  = Image.open(frame_paths[NUM_FRAMES // 2]).convert("RGB")
mid_img  = mid_img.resize((FRAME_SIZE, FRAME_SIZE), Image.BILINEAR)
mid_np   = np.array(mid_img, dtype=np.float32) / 255.0   # (H, W, 3) in [0, 1]

# Upsample mean feature map → same size as input frame (for overlay)
mean_feat    = feat_np[:832].mean(axis=0)                                  # (H', W')
mean_t       = torch.tensor(mean_feat).unsqueeze(0).unsqueeze(0)           # (1,1,H',W')
mean_up      = F.interpolate(mean_t, (FRAME_SIZE, FRAME_SIZE),
                              mode="bilinear", align_corners=False)
mean_up_np   = mean_up[0, 0].numpy()
mean_norm    = (mean_up_np - mean_up_np.min()) / (mean_up_np.max() - mean_up_np.min() + 1e-8)
heatmap_rgb  = cm.jet(mean_norm)[:, :, :3]                                  # (H, W, 3)
overlay      = 0.55 * mid_np + 0.45 * heatmap_rgb                          # blended

# ---- Plot ----
fig = plt.figure(figsize=(20, 9))
gs  = gridspec.GridSpec(2, 5, figure=fig, wspace=0.22, hspace=0.38)

# Row 0 — Input frames
for col, frame_idx in enumerate([0, 5, 10, 15]):
    ax  = fig.add_subplot(gs[0, col])
    img = Image.open(frame_paths[frame_idx]).convert("RGB").resize((224, 224))
    ax.imshow(img)
    ax.set_title(f"frame[{frame_idx}]  {os.path.basename(frame_paths[frame_idx])}", fontsize=8)
    ax.axis("off")

# Row 0, last col — y-coordinate channel (visual sanity check: should be a vertical gradient)
ax = fig.add_subplot(gs[0, 4])
im = ax.imshow(feat_np[833], cmap="coolwarm", interpolation="nearest",
               vmin=-1, vmax=1)
ax.set_title(f"y-coord channel [833]\n(should be top↑ to bottom↓ gradient)", fontsize=8)
plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
ax.axis("off")

# Row 1 — Feature maps
# Mean visual feature map
ax = fig.add_subplot(gs[1, 0])
im = ax.imshow(mean_feat, cmap="viridis", interpolation="nearest")
ax.set_title(f"Mean across 832 ch\n({H_prime}×{H_prime} spatial map)", fontsize=8)
plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
ax.axis("off")

# Three individual channels
for col, ch in enumerate([0, 200, 600]):
    ax = fig.add_subplot(gs[1, col + 1])
    im = ax.imshow(feat_np[ch], cmap="plasma", interpolation="nearest")
    ax.set_title(f"Channel {ch}\n({H_prime}×{H_prime})", fontsize=8)
    plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
    ax.axis("off")

# Overlay: mean heatmap on middle frame
ax = fig.add_subplot(gs[1, 4])
ax.imshow(overlay)
ax.set_title(f"Heatmap overlay\n(mean feat on frame[{NUM_FRAMES//2}])", fontsize=8)
ax.axis("off")

plt.suptitle(
    f"VideoEncoder sanity check — '{os.path.basename(VIDEO_DIR)}'\n"
    f"Input: (1, 3, {NUM_FRAMES}, {FRAME_SIZE}, {FRAME_SIZE}) → "
    f"Output: {tuple(feat_map.shape[1:])}",
    fontsize=11
)
plt.tight_layout()
plt.show()
print("✅  Done!")

"""# Decoder — Decoding with Dynamic Filters

Implements Section 3.3 of Gavrilyuk et al. (CVPR 2018).

**Plain-English summary of what this block does:**
The textual encoder gave us one 300-dim vector that *describes* the actor/action.
The decoder turns that description into three little "stamps" (called *dynamic
filters*) and presses each stamp onto the video feature map. Wherever the stamp
matches the video, we get a bright spot — that's the segmentation.

We do this at three zoom levels (32×32, 128×128, 512×512) so the model gets both
coarse location and fine detail. The biggest one (512×512) is the final mask.

We build it in four small pieces so each can be tested on its own:

| Piece | Class | Input → Output |
|-------|-------|----------------|
| 1 | `DynamicFilterGenerator` | sentence `(B,300)` → 3 filters |
| 2 | `DeconvBlock`            | feature map → ×4 bigger feature map |
| 3 | `Decoder`               | filters + video feat → 3 response maps |
| 4 | `ActorActionSegmenter`  | glues text + video + decoder together |

**One channel-count note (important):** the paper draws the 32×32 filter as
`1×1×832`. But *your* `VideoEncoder` appends 2 coordinate channels, so its output
is **834** channels, not 832. The filter must match whatever the feature actually
has — so we use **834** for the 32×32 level. The other two levels (256, 128) come
out of the deconv blocks and match the paper exactly.

"""

# ---------------------------------------------------------------------------
# DECODER CELL 1 — DynamicFilterGenerator
#
# Paper (Sec 3.3, Eq. 1):
#   f_r = tanh(W_r · T + b_r)
#   "we generate dynamic filters for several resolutions with different
#    network parameters."  + "better results with a tanh activation."
#
# One Linear layer per resolution. Each produces a 1-D filter whose length
# equals the channel count of the video feature at that resolution.
# ---------------------------------------------------------------------------

class DynamicFilterGenerator(nn.Module):
    """
    Sentence vector  ->  three dynamic filters (one per resolution).

    Input
    -----
    T : (B, 300)   sentence vector from the TextualEncoder

    Output
    ------
    dict with keys 32, 128, 512:
        filters[32]  : (B, ch_32)    convolved with the 32x32  video feature
        filters[128] : (B, ch_128)   convolved with the 128x128 video feature
        filters[512] : (B, ch_512)   convolved with the 512x512 video feature

    Why a dict keyed by resolution?
        Keeps the wiring explicit and readable — when the Decoder asks for
        "the filter for the 128 map" there is no ambiguity.
    """

    def __init__(self, text_dim: int = 300,
                 ch_32: int = 834, ch_128: int = 256, ch_512: int = 128):
        super().__init__()
        # ch_32 = 834 because VideoEncoder appends 2 coord channels to 832.
        self.fc_32  = nn.Linear(text_dim, ch_32)
        self.fc_128 = nn.Linear(text_dim, ch_128)
        self.fc_512 = nn.Linear(text_dim, ch_512)

    def forward(self, T: torch.Tensor) -> dict:
        # tanh squashes each filter weight into [-1, 1]  (paper's choice)
        return {
            32:  torch.tanh(self.fc_32(T)),    # (B, 834)
            128: torch.tanh(self.fc_128(T)),   # (B, 256)
            512: torch.tanh(self.fc_512(T)),   # (B, 128)
        }

# ---------------------------------------------------------------------------
# DECODER CELL 2 — DeconvBlock
#
# Paper (Sec 3.3, Details):
#   "Each of our deconvolutional networks consists of two blocks with one
#    deconvolutional layer with kernel size 8x8 and stride 4, followed by a
#    convolutional layer with a kernel size of 3x3 and a stride of 1."
#
#   Crucial detail: deconv is applied to the VIDEO FEATURE, not the response
#   map. "Different from [6, 15], who apply deconvolution on the segmentation
#    response maps, we use the deconvolutional layers on the video
#    representation V_r directly."
#
# One DeconvBlock = upsample x4 (32->128 or 128->512).
#   ConvTranspose2d(k=8, s=4, padding=2) gives an EXACT x4 size increase.
#   (output = (in-1)*stride - 2*pad + kernel = (32-1)*4 - 4 + 8 = 128 ✓)
# ---------------------------------------------------------------------------

class DeconvBlock(nn.Module):
    """
    Upsample a video feature map by exactly 4x in height and width.

    in_ch  channels  ->  out_ch channels
    H x W            ->  4H x 4W

    Example: (B, 834, 32, 32) -> (B, 256, 128, 128)
    """

    def __init__(self, in_ch: int, out_ch: int):
        super().__init__()
        # Upsample x4. padding=2 with k=8,s=4 lands on a clean 4x multiple.
        self.deconv = nn.ConvTranspose2d(in_ch, out_ch,
                                         kernel_size=8, stride=4, padding=2)
        # Refine, keep the size (k=3, s=1, padding=1 preserves H,W).
        self.conv = nn.Conv2d(out_ch, out_ch, kernel_size=3, stride=1, padding=1)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        x = F.relu(self.deconv(x))   # (B, out_ch, 4H, 4W)
        x = F.relu(self.conv(x))     # same size, refined
        return x

# ---------------------------------------------------------------------------
# DECODER CELL 3 — dynamic convolution helper + Decoder
#
# Paper (Sec 3.3, Eq. 2):   S_r = f_r * V_r
#   The dynamic filter is 1x1 spatially, so "convolving" it with the video
#   feature is just a per-pixel dot product across the channel axis:
#       response(i,j) = sum_c  filter[c] * video[c, i, j]
#   We implement it with a broadcasted multiply + channel sum. This handles a
#   *different* filter per batch sample (which a normal nn.Conv2d cannot).
# ---------------------------------------------------------------------------

def dynamic_conv(feature: torch.Tensor, filt: torch.Tensor) -> torch.Tensor:
    """
    Per-sample 1x1 dynamic convolution.

    feature : (B, C, H, W)   video feature at some resolution
    filt    : (B, C)         dynamic filter for that resolution (one per sample)

    returns : (B, 1, H, W)   response (segmentation logits at that resolution)
    """
    # filt[:, :, None, None] -> (B, C, 1, 1) so it broadcasts over H, W.
    return (feature * filt[:, :, None, None]).sum(dim=1, keepdim=True)


class Decoder(nn.Module):
    """
    Decoder — Gavrilyuk et al. CVPR 2018, Section 3.3.

    Inputs
    ------
    T          : (B, 300)          sentence vector  (TextualEncoder output)
    video_feat : (B, 834, 32, 32)  video feature    (VideoEncoder output)

    Output
    ------
    dict of response maps (raw logits, NOT yet sigmoid-ed):
        32  : (B, 1, 32,  32)
        128 : (B, 1, 128, 128)
        512 : (B, 1, 512, 512)   <- final segmentation mask

    Flow (matches Figure 2, left-to-right):
        video_feat (834ch, 32)  --filter32-->  response 32
                  |
              deconv1 (834->256, x4)
                  v
        video_feat (256ch, 128) --filter128--> response 128
                  |
              deconv2 (256->128, x4)
                  v
        video_feat (128ch, 512) --filter512--> response 512  (final)
    """

    def __init__(self, text_dim: int = 300, video_ch: int = 834):
        super().__init__()
        self.filters = DynamicFilterGenerator(
            text_dim=text_dim, ch_32=video_ch, ch_128=256, ch_512=128)
        self.deconv1 = DeconvBlock(in_ch=video_ch, out_ch=256)   # 32  -> 128
        self.deconv2 = DeconvBlock(in_ch=256,      out_ch=128)   # 128 -> 512

    def forward(self, T: torch.Tensor, video_feat: torch.Tensor) -> dict:
        f = self.filters(T)   # dict: {32: (B,834), 128: (B,256), 512: (B,128)}

        # --- 32x32: filter the raw video feature directly ---
        v32 = video_feat                       # (B, 834, 32, 32)
        s32 = dynamic_conv(v32, f[32])         # (B, 1, 32, 32)

        # --- 128x128: deconv the video feature, then filter ---
        v128 = self.deconv1(v32)               # (B, 256, 128, 128)
        s128 = dynamic_conv(v128, f[128])      # (B, 1, 128, 128)

        # --- 512x512: deconv again, then filter -> final mask ---
        v512 = self.deconv2(v128)              # (B, 128, 512, 512)
        s512 = dynamic_conv(v512, f[512])      # (B, 1, 512, 512)

        return {32: s32, 128: s128, 512: s512}

# ---------------------------------------------------------------------------
# DECODER CELL 4 — ActorActionSegmenter  (the full model)
#
# Wires the three components together exactly as in handoff.md Step 2.
#   text_encoder  : TextualEncoder   (already defined above)
#   video_encoder : VideoEncoder     (already defined above)
#   decoder       : Decoder          (defined in DECODER CELL 3)
# ---------------------------------------------------------------------------

class ActorActionSegmenter(nn.Module):
    """
    Full end-to-end model: (video, sentence_embedding) -> 3 response maps.

    forward inputs
    --------------
    video              : (B, 3, N, 512, 512)   N RGB frames, values in [-1, 1]
    sentence_embedding : (B, max_len, 300)     padded word2vec matrices

    forward output
    --------------
    dict {32, 128, 512} of response maps (logits). Use [512] as the mask.
    """

    def __init__(self, text_encoder: nn.Module,
                 video_encoder: nn.Module,
                 decoder: nn.Module):
        super().__init__()
        self.text_encoder  = text_encoder
        self.video_encoder = video_encoder
        self.decoder       = decoder

    def forward(self, video: torch.Tensor,
                sentence_embedding: torch.Tensor) -> dict:
        text_feat  = self.text_encoder(sentence_embedding)   # (B, 300)
        video_feat = self.video_encoder(video)               # (B, 834, 32, 32)
        masks      = self.decoder(text_feat, video_feat)     # 3 response maps
        return masks

# ---------------------------------------------------------------------------
# DECODER CELL 5 — Multi-resolution logistic loss
#
# Paper (Sec 3.4, Eqs. 3-5):
#   L      = sum_r  alpha_r * L_r          (alpha_r = 1 for r in {32,128,512})
#   L_r    = mean over pixels of L_r_ij
#   L_r_ij = log(1 + exp(-S_r_ij * Y_r_ij))   (logistic loss)
#
# Y_r_ij is +1 for actor/action pixels, -1 for background.
# We get the lower-res ground truths by downsampling the 512 mask.
# ---------------------------------------------------------------------------

def make_multiscale_targets(mask_512: torch.Tensor) -> dict:
    """
    Build {32, 128, 512} ground-truth masks from one 512x512 binary mask.

    mask_512 : (B, 1, 512, 512)  with values in {0, 1}

    returns  : dict of (B, 1, r, r) tensors with values in {-1, +1}
               (+1 = actor/action, -1 = background) as the paper's loss needs.
    """
    targets = {}
    for r in (32, 128, 512):
        m = F.interpolate(mask_512, size=(r, r), mode="nearest")  # (B,1,r,r) in {0,1}
        targets[r] = m * 2.0 - 1.0                                # {0,1} -> {-1,+1}
    return targets


def multiresolution_loss(responses: dict, targets: dict,
                         alphas: dict = None) -> torch.Tensor:
    """
    responses : dict {32,128,512} of (B,1,r,r) raw logits (model output)
    targets   : dict {32,128,512} of (B,1,r,r) in {-1,+1}  (from make_multiscale_targets)
    alphas    : per-resolution weights; paper uses 1.0 for all.

    returns   : scalar loss tensor.
    """
    if alphas is None:
        alphas = {32: 1.0, 128: 1.0, 512: 1.0}

    total = 0.0
    for r in (32, 128, 512):
        S = responses[r]      # (B,1,r,r)
        Y = targets[r]        # (B,1,r,r) in {-1,+1}
        # log(1 + exp(-S*Y)) is numerically the softplus of (-S*Y).
        L_r = F.softplus(-S * Y).mean()   # mean over all pixels & batch
        total = total + alphas[r] * L_r
    return total

# ---------------------------------------------------------------------------
# DECODER CELL 6 — Sanity check (shapes only, no training)
#
# Run this AFTER the textual encoder and video encoder cells above so that
# `encoder` (text), `i3d_backbone`, and the classes are all defined.
#
# This uses RANDOM inputs to confirm the decoder wiring produces the right
# shapes. Swap in a real video + sentence once shapes look correct.
# ---------------------------------------------------------------------------

print("=" * 60)
print("Decoder — Shape Sanity Check")
print("=" * 60)

B = 2
text_dim = 300
VIDEO_CH = 834   # 832 visual + 2 coord channels from VideoEncoder

# --- Build just the decoder and test it in isolation (fast, no I3D needed) ---
decoder = Decoder(text_dim=text_dim, video_ch=VIDEO_CH).to(device)
decoder.eval()

dummy_text  = torch.randn(B, text_dim, device=device)          # (B, 300)
dummy_video = torch.randn(B, VIDEO_CH, 32, 32, device=device)  # (B, 834, 32, 32)

with torch.no_grad():
    responses = decoder(dummy_text, dummy_video)

print("\nResponse map shapes:")
for r in (32, 128, 512):
    print(f"  {r:>3} : {tuple(responses[r].shape)}")

expected = {32: (B,1,32,32), 128: (B,1,128,128), 512: (B,1,512,512)}
ok = all(tuple(responses[r].shape) == expected[r] for r in expected)
print("\nAll shapes correct:" , "YES ✓" if ok else "NO ✗")

# --- Test the loss too, with a fake ground-truth mask ---
fake_mask = (torch.rand(B, 1, 512, 512, device=device) > 0.5).float()
targets   = make_multiscale_targets(fake_mask)
loss      = multiresolution_loss(responses, targets)
print(f"Loss on random data: {loss.item():.4f}  (sanity: should be a positive number)")

print(f"\nDecoder parameters: {sum(p.numel() for p in decoder.parameters()):,}")

"""# Prediction — Full Model on One Real Video

This runs the complete pipeline end-to-end on a real video folder + a sentence,
then shows the three response maps. The weights are **randomly initialised**
(we have not trained yet), so the mask will look like noise — that is expected.
The point here is to prove the whole pipeline runs end-to-end and produces a
512×512 mask. Training comes next (handoff.md Step 4).

"""

# ---------------------------------------------------------------------------
# PREDICTION CELL — end-to-end forward pass on a real video
#
# Requires (all defined in the cells above):
#   word2vec, sentence_to_embedding, TextualEncoder
#   load_video_frames, VideoEncoder, i3d_backbone
#   Decoder, ActorActionSegmenter
# ---------------------------------------------------------------------------

# ---- CONFIGURE THIS ----
VIDEO_DIR  = "/content/JPEGImages/0a2f2bd294"     # same folder used earlier
SENTENCE   = "the glass of a motorbike that s riding down a highway"
NUM_FRAMES = 16
FRAME_SIZE = 512          # 512 = paper-accurate. Use 224 if you hit OOM.
MAX_LEN    = 20

# ---- 1. Build the three components ----
text_encoder  = TextualEncoder(embed_dim=300, kernel_size=2).to(device)
video_encoder = VideoEncoder(i3d_backbone.to(device)).to(device)
decoder       = Decoder(text_dim=300, video_ch=834).to(device)

model = ActorActionSegmenter(text_encoder, video_encoder, decoder).to(device)
model.eval()
print(f"Full model parameters: {sum(p.numel() for p in model.parameters()):,}")

# ---- 2. Prepare the two inputs ----
# Video  -> (1, 3, N, H, W)
video_tensor, frame_paths = load_video_frames(VIDEO_DIR, NUM_FRAMES, FRAME_SIZE)
video_tensor = video_tensor.to(device)

# Sentence -> (1, max_len, 300)
emb = sentence_to_embedding(SENTENCE, word2vec, MAX_LEN)   # (max_len, 300)
emb = emb.unsqueeze(0).to(device)                          # (1, max_len, 300)

print(f"\nVideo tensor    : {tuple(video_tensor.shape)}")
print(f"Sentence tensor : {tuple(emb.shape)}   ('{SENTENCE}')")

# ---- 3. Forward pass ----
print("\nRunning full model (I3D forward can take ~60s on CPU)...")
with torch.no_grad():
    responses = model(video_tensor, emb)      # dict {32, 128, 512}

print("\nResponse maps:")
for r in (32, 128, 512):
    print(f"  {r:>3} : {tuple(responses[r].shape)}")

# ---- 4. Turn the final 512 logits into a probability mask ----
final_logits = responses[512]                 # (1, 1, 512, 512)
final_mask   = torch.sigmoid(final_logits)    # probabilities in [0, 1]
print(f"\nFinal mask range: [{final_mask.min():.3f}, {final_mask.max():.3f}]  "
      f"(untrained -> expect ~0.5 noise)")

# ---- 5. Visualise: middle frame, raw heatmap, thresholded mask ----
mid_idx   = len(frame_paths) // 2
mid_frame = Image.open(frame_paths[mid_idx]).convert("RGB").resize((FRAME_SIZE, FRAME_SIZE))
heat      = final_mask[0, 0].cpu().numpy()

fig, ax = plt.subplots(1, 3, figsize=(15, 5))
ax[0].imshow(mid_frame);            ax[0].set_title("Middle frame");       ax[0].axis("off")
ax[1].imshow(heat, cmap="jet");     ax[1].set_title("Response (sigmoid)"); ax[1].axis("off")
ax[2].imshow(mid_frame)
ax[2].imshow(heat > 0.5, cmap="Reds", alpha=0.5)
ax[2].set_title("Mask overlay (>0.5)"); ax[2].axis("off")
plt.suptitle(f'"{SENTENCE}"  —  UNTRAINED model (noise is expected)', fontsize=12)
plt.tight_layout(); plt.show()

"""# Real Loss — Section 3.4, with Ground-Truth Annotations

The earlier prediction cell used a *random* mask, so its loss was meaningless.
Now we have real annotations, so we can compute the actual training loss.

**What Section 3.4 needs (Eqs. 3-5):**

```
L       = Σ_r  α_r · L_r            α_r = 1  for r ∈ {32, 128, 512}
L_r     = (1/r²) Σ_i Σ_j  L_r_ij           ← mean over the r×r pixels
L_r_ij  = log(1 + exp(−S_r_ij · Y_r_ij))   ← logistic loss
```

- `S_r_ij` = our model's response value at pixel (i,j), resolution r  (the logits)
- `Y_r_ij` = ground-truth label: **+1** actor/action pixel, **−1** background

**Two facts that decide how we read the annotation:**

1. *Which frame?* Section 3.4: the ground truth is "the frame in the **middle**
   of each input video clip." We segment the middle frame, so we load the mask
   for that one frame only.

2. *What format?* Your `Annotations/0a2f2bd294/00000.png ...` are YouTube-VOS
   **palette PNGs**: each pixel stores a class *index* (0 = background, 1,2,…
   = object instances). The red colour you see is just the palette — the real
   value is the index. So "actor pixel" = `index > 0`. We read the index map
   directly (`np.array(Image.open(...))`), **not** the RGB colours.

"""

# ---------------------------------------------------------------------------
# REAL-LOSS CELL 1 — load_annotation_mask
#
# Reads ONE YouTube-VOS palette-PNG annotation and returns a binary mask
# tensor (1, 1, 512, 512) with values in {0, 1}.
#
#   index 0   -> background -> 0
#   index >=1 -> any object -> 1   (actor/action)
#
# We read the raw palette indices (np.array on a 'P'-mode image), NOT RGB.
# ---------------------------------------------------------------------------

def load_annotation_mask(anno_path: str, size: int = 512) -> torch.Tensor:
    """
    Load one annotation PNG -> binary mask tensor.

    Parameters
    ----------
    anno_path : path to a single mask PNG, e.g.
                ".../Annotations/0a2f2bd294/00045.png"
    size      : resize the mask to (size, size). 512 = paper-accurate.

    Returns
    -------
    torch.FloatTensor  (1, 1, size, size)  values in {0, 1}
    """
    m = Image.open(anno_path)            # 'P' mode: pixel values are class indices
    idx = np.array(m)                    # (H, W) ints; 0=bg, >=1=object
    binary = (idx > 0).astype(np.float32)  # any object -> 1, background -> 0

    t = torch.from_numpy(binary)[None, None]   # (1, 1, H, W)
    # nearest-neighbour so we never invent fractional labels between 0 and 1
    t = F.interpolate(t, size=(size, size), mode="nearest")
    return t


def middle_frame_anno_path(anno_video_dir: str, frame_paths: list) -> str:
    """
    Pick the annotation PNG that matches the MIDDLE sampled video frame.

    The video frame files and the annotation files share the same names
    (00045.jpg  <->  00045.png), so we take the middle frame_path, swap the
    folder and the extension.

    Parameters
    ----------
    anno_video_dir : ".../Annotations/0a2f2bd294"
    frame_paths    : list of sampled JPEG paths from load_video_frames()
    """
    mid_jpg = frame_paths[len(frame_paths) // 2]          # e.g. ".../00045.jpg"
    stem    = os.path.splitext(os.path.basename(mid_jpg))[0]  # "00045"
    return os.path.join(anno_video_dir, stem + ".png")

# ---------------------------------------------------------------------------
# REAL-LOSS CELL 2 — compute the real Section-3.4 loss on one sample
#
# Requires (from the cells above):
#   model (ActorActionSegmenter), word2vec, sentence_to_embedding,
#   load_video_frames, make_multiscale_targets, multiresolution_loss
#
# And the prediction cell's `responses`, `video_tensor`, `frame_paths`,
# `SENTENCE` — re-run that cell first if they are not in memory.
# ---------------------------------------------------------------------------

# ---- CONFIGURE: point this at the Annotations folder for the SAME video ----
# JPEGImages/0a2f2bd294  ->  Annotations/0a2f2bd294
ANNO_VIDEO_DIR = "/content/Annotations/0a2f2bd294"

# ---- 1. Find the annotation for the middle frame ----
anno_path = middle_frame_anno_path(ANNO_VIDEO_DIR, frame_paths)
print("Middle-frame annotation:", anno_path)

# ---- 2. Load it as a (1,1,512,512) binary mask ----
gt_mask_512 = load_annotation_mask(anno_path, size=512).to(device)
obj_frac = gt_mask_512.mean().item()
print(f"Ground-truth mask : {tuple(gt_mask_512.shape)}  "
      f"object pixels = {obj_frac*100:.1f}%")

# ---- 3. Build the {-1,+1} targets at all three resolutions (Sec 3.4) ----
targets = make_multiscale_targets(gt_mask_512)
for r in (32, 128, 512):
    pos = (targets[r] > 0).float().mean().item()
    print(f"  target[{r:>3}] : {tuple(targets[r].shape)}  +1 pixels = {pos*100:.1f}%")

# ---- 4. Compute the REAL multi-resolution logistic loss ----
# (responses comes from the PREDICTION cell — model output on this video)
with torch.no_grad():
    # per-resolution breakdown so you can see each term
    print("\nPer-resolution logistic loss (L_r):")
    for r in (32, 128, 512):
        S, Y = responses[r], targets[r]
        L_r = F.softplus(-S * Y).mean()       # = mean log(1+exp(-S*Y))
        print(f"  L_{r:<3} = {L_r.item():.4f}   (alpha_{r} = 1)")

    total_loss = multiresolution_loss(responses, targets)

print(f"\nTotal loss  L = Σ_r α_r L_r = {total_loss.item():.4f}")
print("(Untrained model -> expect roughly log(2) ≈ 0.69 per term, so total ≈ 2.1.")
print(" Training drives this DOWN. This is now a REAL loss, not random.)")

# ---------------------------------------------------------------------------
# REAL-LOSS CELL 3 — visualise prediction vs ground truth
#
# Side by side: middle frame, ground-truth mask, model response (untrained).
# ---------------------------------------------------------------------------

mid_idx   = len(frame_paths) // 2
mid_frame = Image.open(frame_paths[mid_idx]).convert("RGB").resize((512, 512))
gt        = gt_mask_512[0, 0].cpu().numpy()
pred      = torch.sigmoid(responses[512])[0, 0].cpu().numpy()

fig, ax = plt.subplots(1, 3, figsize=(15, 5))
ax[0].imshow(mid_frame);                  ax[0].set_title("Middle frame");        ax[0].axis("off")
ax[1].imshow(gt, cmap="gray");            ax[1].set_title("Ground truth (Y)");    ax[1].axis("off")
ax[2].imshow(pred, cmap="jet");           ax[2].set_title("Model response (untrained)"); ax[2].axis("off")
plt.suptitle(f'"{SENTENCE}"  —  loss computed against REAL annotation', fontsize=12)
plt.tight_layout(); plt.show()